const settings = require('../settings');
const fs = require('fs');
const path = require('path');

async function helpCommand(sock, chatId, message) {
    const start = Date.now();
    let theme;
    try {
        const { getTheme } = require('./theme');
        theme = getTheme();
    } catch {
        theme = { name: 'Batman', emoji: '🦇', banner: '🦇 *IANENIGMA MD BOT* 🦇', quote: '"I am vengeance. I am the night."', border: '▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓', divider: '━━━━━━━━━━━━━━━━━━━━━━━━━', bullet: '▸', accent: '🖤' };
    }
    let mode = 'Public';
    try {
        const data = JSON.parse(fs.readFileSync('./data/messageCount.json'));
        if (typeof data.isPublic === 'boolean') mode = data.isPublic ? 'Public' : 'Private';
    } catch (_) {}
    const ping = Date.now() - start;
    const ramMB = Math.round(process.memoryUsage().rss / 1024 / 1024);
    const uptimeSec = Math.floor(process.uptime());
    const uptimeStr = Math.floor(uptimeSec / 3600) + 'h ' + Math.floor((uptimeSec % 3600) / 60) + 'm';
    const userName = message.pushName || 'User';
    const now = new Date();
    const ugandaHour = new Date(now.getTime() + now.getTimezoneOffset() * 60000 + 3 * 3600000).getHours();
    const sleeping = ugandaHour >= 1 && ugandaHour < 6;
    const version = settings.version || 'v4.0.0';
    const B = theme.bullet;
    const D = theme.divider;
    const lines = [
        '🦇 *I A N E N I G M A  M D* 🦇',
        '━━━━━━━━━━━━━━━━━━━━━━━━━',
        theme.banner,
        '_' + theme.quote + '_',
        '',
        '┌─── ' + theme.emoji + ' *WELCOME, ' + userName.toUpperCase() + '*',
        '│ 📡 Ping: *' + ping + 'ms*',
        '│ ⏱️ Uptime: *' + uptimeStr + '*',
        '│ 💾 RAM: *' + ramMB + 'MB*',
        '│ 🔓 Mode: *' + mode + '*',
        '│ 🌙 Sleep: *' + (sleeping ? 'ON — 1am-6am 🇺🇬' : 'OFF (Active)') + '*',
        '│ 🎨 Theme: *' + theme.name + '*',
        '│ 🔖 Version: *' + version + '*',
        '└────────────────────────────',
        '',
        D, '⚡ *GENERAL*', D,
        B + ' .help / .menu      — This menu',
        B + ' .ping              — Bot ping & live stats',
        B + ' .alive             — Bot status message',
        B + ' .owner             — Contact owner',
        B + ' .id / .jid         — Get WhatsApp JID info',
        B + ' .repo              — View bot repository',
        B + ' .stats             — Command usage stats',
        B + ' .today             — Fun fact of the day',
        B + ' .tts <text>        — Text to speech',
        B + ' .joke              — Random joke',
        B + ' .quote             — Random quote',
        B + ' .fact              — Random fact',
        B + ' .weather <city>    — Live weather + 3-day forecast',
        B + ' .news              — Latest headlines (based on your location)',
        B + ' .8ball <question>  — Magic 8-ball',
        B + ' .groupinfo         — Show group details',
        B + ' .vv                — Open view-once media',
        B + ' .trt <txt> <lang>  — Translate text',
        B + ' .github <user>     — GitHub profile lookup',
        B + ' .staff             — Bot staff list',
        B + ' .ianenigma         — About the creator & this bot',
        B + ' .setlocation <city>  — Set your location/timezone',
        B + ' .mylocation          — View saved location & local time',
        B + ' .localtime           — Show current time in your timezone',
        B + ' .locationfact        — Fun fact about your country',
        B + ' .creator           — Same as .ianenigma',
        B + ' .report <reason>   — Report issue to admin',
        '',
        D, '🎵 *MUSIC & ENTERTAINMENT*', D,
        B + ' .top10songs            — Top 10 mixed hits (random each time)',
        B + ' .top10songs throwback  — Old school classics',
        B + ' .top10songs fresh      — Latest 2024 hits',
        B + ' .netflix               — New Netflix releases',
        B + ' .netflix movies        — Movies only',
        B + ' .netflix series        — Series/shows only',
        B + ' .netflix top           — Highest rated titles',
        B + ' .play <song>           — YouTube audio',
        B + ' .song <name>           — Download song MP3',
        B + ' .video <name>          — YouTube video download',
        B + ' .spotify <query>       — Spotify search',
        B + ' .aimusic <mood>        — Music by mood (happy/sad/chill/hype/afro...)',
        '',
        D, '👮 *ADMIN COMMANDS*', D,
        B + ' .ban @user        — Ban member',
        B + ' .unban @user      — Unban member',
        B + ' .promote @user    — Make admin',
        B + ' .demote @user     — Remove admin',
        B + ' .mute <mins>      — Mute group',
        B + ' .unmute           — Unmute group',
        B + ' .kick @user       — Remove member',
        B + ' .delete / .del    — Delete a message',
        B + ' .warn @user       — Issue warning (3 = autokick)',
        B + ' .warnings @user   — Check warnings',
        B + ' .clearwarn @user  — Clear warnings',
        B + ' .antilink         — Toggle antilink filter',
        B + ' .antibadword      — Bad-word filter',
        B + ' .antitag on/off   — Anti-tag toggle',
        B + ' .antiflood on/off — Flood protection',
        B + ' .antiraid on/off  — Raid auto-lockdown',
        B + ' .clear            — Clear bot messages',
        B + ' .tag <msg>        — Tag with message',
        B + ' .tagall           — Tag all members',
        B + ' .tagadmins <msg>  — Tag admins only',
        B + ' .tagnotadmin      — Tag non-admins',
        B + ' .everyone <msg>   — Ping all members',
        B + ' .hidetag <msg>    — Hidden silent tag',
        B + ' .inactive <days>  — List inactive members',
        '',
        D, '🏰 *GROUP MANAGEMENT*', D,
        B + ' .lockmode on/off      — Lock group (admins only)',
        B + ' .link                 — Get group invite link',
        B + ' .resetlink            — Reset invite link',
        B + ' .rules                — Show group rules',
        B + ' .rules set <text>     — Set group rules (admin)',
        B + ' .rules clear          — Clear rules (admin)',
        B + ' .welcome on/off       — Welcome message toggle',
        B + ' .goodbye on/off       — Goodbye message toggle',
        B + ' .chatbot              — Toggle AI chatbot mode',
        B + ' .autoreply add t|r    — Add custom auto-reply',
        B + ' .autoreply remove <t> — Remove auto-reply',
        B + ' .autoreply list       — View all auto-replies',
        B + ' .autoreply clear      — Clear all auto-replies',
        B + ' .setgdesc <text>      — Set group description',
        B + ' .setgname <name>      — Set group name',
        B + ' .setgpp               — Set group photo',
        B + ' .topmembers           — Most active members',
        B + ' .poll <q|op1|op2>     — Create a poll',
        B + ' .schedule             — Schedule messages',
        B + ' .broadcast <msg>      — Send to all groups',
        '',
        D, '🔒 *OWNER ONLY*', D,
        B + ' .setprefix <symbol>   — Change command prefix (e.g. ! / # $)',
        B + ' .setprefix show       — Show current prefix',
        B + ' .mode public/private',
        B + ' .autotyping on/off',
        B + ' .autoread on/off',
        B + ' .autostatus on/off',
        B + ' .antidelete on/off',
        B + ' .anticall on/off',
        B + ' .pmblocker on/off',
        B + ' .setpp                — Set bot profile picture',
        B + ' .setmenuimage         — Set menu banner image',
        B + ' .setbio <text>        — Set bot bio/status',
        B + ' .setrepo <url>        — Set bot GitHub repo',
        B + ' .setrepo name <name>  — Set repo display name',
        B + ' .cleartmp             — Clear temp files',
        B + ' .clearsession         — Clear session data',
        B + ' .settings             — View all bot settings',
        B + ' .areact on/off        — Auto reactions toggle',
        B + ' .sudo @user           — Add sudo user',
        B + ' .update               — Update bot files',
        B + ' .theme <name>         — Change theme (DC or Marvel)',
        '',
        D, '🛡️ *BAN PROTECTION*', D,
        B + ' .antiban on/off       — Bio rotation antiban',
        B + ' .antiban <mins>       — Set rotation interval',
        B + ' .antiban status       — Check antiban status',
        B + ' .banprotection        — View ALL active protections',
        B + ' .protection           — Same as .banprotection',
        '',
        D, '🤖 *AI & SMART FEATURES*', D,
        B + ' .gpt <question>    — ChatGPT AI response (English)',
        B + ' .gemini <question> — Google Gemini AI (English)',
        B + ' .imagine <prompt>  — AI image generation',
        B + ' .flux <prompt>     — Flux AI image generation',
        B + ' .sora <prompt>     — Sora AI video generation',
        B + ' .roast @user       — AI-powered roast',
        B + ' .compliment @user  — AI compliment',
        B + ' .remind <t> <msg>  — Set a reminder (.remindme also works)',
        B + ' .afk <reason>      — Set yourself as AFK',
        '',
        D, '🧠 *FUN & TESTS*', D,
        B + ' .adhdtest start    — ADHD screening (18 questions)',
        B + ' .adhdtest cancel   — Cancel active test',
        B + ' .trivia            — Random trivia question',
        B + ' .answer <answer>   — Answer the trivia',
        B + ' .truth             — Truth or dare — truth',
        B + ' .dare              — Truth or dare — dare',
        B + ' .hangman           — Hangman word game',
        B + ' .guess <letter>    — Guess a letter',
        B + ' .tictactoe @user   — TicTacToe vs user',
        '',
        D, '🛠️ *TOOLS*', D,
        B + ' .calc <expr>       — Calculator',
        B + ' .qr <text/url>     — Generate QR code',
        B + ' .getpp @user       — Get profile picture',
        B + ' .ss <url>          — Screenshot website',
        B + ' .translate <text>  — Translate any language',
        '',
        D, '🎨 *MEDIA & STICKERS*', D,
        B + ' .sticker           — Image/video to sticker',
        B + ' .simage            — Sticker to image',
        B + ' .steal             — Steal a sticker',
        B + ' .take <name>       — Rename sticker',
        B + ' .removebg          — Remove background',
        B + ' .remini            — AI enhance image',
        B + ' .crop              — Crop sticker',
        B + ' .emojimix e1+e2    — Mix two emojis',
        B + ' .meme              — Random meme',
        B + ' .attp <text>       — Text to sticker',
        B + ' .blur              — Blur image',
        '',
        D, '📥 *DOWNLOADERS*', D,
        B + ' .instagram <url>   — Instagram photo/video',
        B + ' .tiktok <url>      — TikTok video',
        B + ' .facebook <url>    — Facebook video',
        B + ' .play / .song      — YouTube audio',
        B + ' .video             — YouTube video',
        '',
        D, '🃏 *FUN & SOCIAL*', D,
        B + ' .insult @user      — Roast someone',
        B + ' .flirt             — Random flirty line',
        B + ' .shayari           — Random poetry',
        B + ' .wasted @user      — Wasted overlay',
        B + ' .ship @user        — Ship compatibility',
        B + ' .simp @user        — Simp card',
        B + ' .stupid @user      — Stupid card',
        B + ' .jail              — Jail overlay',
        B + ' .triggered         — Triggered GIF',
        B + ' .tweet             — Fake tweet',
        B + ' .ytcomment         — Fake YouTube comment',
        B + ' .oogway            — Oogway wisdom',
        B + ' .pair @user        — Pair with user',
        B + ' .hug / .kiss / .pat / .poke / .cry / .wink',
        '',
        D, '🎨 *THEMES — .theme list*', D,
        '🦇 *DC:* batman · superman · joker',
        '⚔️  wonderwoman · flash · greenlantern',
        '🔱 aquaman · harleyquinn · arrow',
        '⭐ shazam · peacemaker · vigilante',
        '━━━━━━━━━━━━━━━━━━━━━━━━━',
        '⚡ *Marvel:* ironman · spiderman · blackpanther',
        '⚡ thor · captainamerica · blackwidow',
        '💚 hulk · doctorstrange · antman',
        '🔴 scarletwitch · wolverine · deadpool',
        '',
        D,
        theme.emoji + ' *IANENIGMA MD ' + version + ' — 185+ Commands*',
        '',
        '📢 *Join our Channel:*',
        'https://whatsapp.com/channel/0029VbCiP1Y1noywqpmoSz2z',
        theme.accent + ' _Type_ *.theme <name>* _to switch · .theme list for all 24_',
        D,
    ];
    const menu = lines.join('\n');
    try {
        // Always use bot_image.jpg — the IANENIGMA Empire image by default,
        // or whatever the owner has set via .setmenuimage
        const menuImgPath = path.join(__dirname, '../assets/bot_image.jpg');
        if (fs.existsSync(menuImgPath)) {
            await sock.sendMessage(chatId, {
                image: fs.readFileSync(menuImgPath),
                caption: menu
            }, { quoted: message });
        } else {
            await sock.sendMessage(chatId, { text: menu }, { quoted: message });
        }
    } catch (err) {
        console.error('help error:', err.message);
        await sock.sendMessage(chatId, { text: menu }, { quoted: message });
    }
}

module.exports = helpCommand;
